export type Grade = 'A' | 'B' | 'C' | 'D' | 'F';

export interface Citation {
  id: string;
  date: string;
  activity: string;
  citationType: 'Willful' | 'Serious' | 'Other';
  standard: string;
  standardDescription: string;
  penalty: number;
  status: 'Paid' | 'Contested' | 'Settled' | 'Pending';
  contested: boolean;
  inspectorNarrative?: string;
}

export interface Contractor {
  id: string;
  name: string;
  trade: string;
  location: string;
  city: string;
  state: string;
  ein: string;
  licenseNumber: string;
  licensedSince: string;
  employees: number;
  grade: Grade;
  gradeLabel: string;
  gradeSummary: string;
  severityScore: number;
  frequencyScore: number;
  recencyScore: number;
  responseScore: number;
  violations36mo: number;
  willfulViolations: number;
  seriousViolations: number;
  otherViolations: number;
  fatalityRecord: boolean;
  lastCitationDate: string;
  peerComparison: string;
  peerPercentile: number;
  citations: Citation[];
  quarterlyViolations: { quarter: string; willful: number; serious: number; other: number }[];
  trendData: { month: string; score: number }[];
  peerGradeDistribution: { grade: Grade; count: number }[];
}

export const gradeColorMap: Record<Grade, string> = {
  A: '#2D5A27',
  B: '#4A7C43',
  C: '#D97706',
  D: '#C2410C',
  F: '#B91C1C',
};

export const gradeLabelMap: Record<Grade, string> = {
  A: 'Excellent',
  B: 'Good',
  C: 'Caution',
  D: 'High Risk',
  F: 'Critical Risk',
};

function quartersFrom(startYear: number, startQ: number, count: number) {
  const result: { quarter: string; willful: number; serious: number; other: number }[] = [];
  let y = startYear;
  let q = startQ;
  for (let i = 0; i < count; i++) {
    const willful = [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0][i] || 0;
    const serious = [1, 2, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0][i] || 0;
    const other = [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0][i] || 0;
    result.push({ quarter: `Q${q} ${y}`, willful, serious, other });
    q++;
    if (q > 4) { q = 1; y++; }
  }
  return result;
}

export const summitRoofing: Contractor = {
  id: 'summit-roofing-llc',
  name: 'Summit Roofing LLC',
  trade: 'Roofing',
  location: 'Houston, TX',
  city: 'Houston',
  state: 'TX',
  ein: '47-8829315',
  licenseNumber: 'TX-ROC-298471',
  licensedSince: '2011',
  employees: 47,
  grade: 'D',
  gradeLabel: 'High Risk',
  gradeSummary: 'Based on 14 citations, 2 willful violations, and 1 fatality record over 72 months',
  severityScore: 74,
  frequencyScore: 61,
  recencyScore: 48,
  responseScore: 55,
  violations36mo: 8,
  willfulViolations: 2,
  seriousViolations: 9,
  otherViolations: 3,
  fatalityRecord: true,
  lastCitationDate: 'Mar 2024',
  peerComparison: 'Worse than 82% of roofers in Houston metro',
  peerPercentile: 82,
  citations: [
    {
      id: 'CIT-2024-001',
      date: '2024-03-15',
      activity: 'Roofing - residential re-roof',
      citationType: 'Willful',
      standard: '1926.502',
      standardDescription: 'Fall Protection Systems Criteria and Practices',
      penalty: 15625,
      status: 'Contested',
      contested: true,
      inspectorNarrative: 'Employer was aware that employees were performing roofing work at heights greater than 6 feet without any fall protection system in place. The employer had been previously cited for the same violation on 2022-06-18. Employees confirmed that no fall protection was provided or required by the employer despite working on a 4:12 pitch roof at approximately 22 feet above grade.',
    },
    {
      id: 'CIT-2023-008',
      date: '2023-11-02',
      activity: 'Commercial flat roof installation',
      citationType: 'Serious',
      standard: '1926.502',
      standardDescription: 'Fall Protection Systems Criteria and Practices',
      penalty: 5420,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2023-005',
      date: '2023-08-17',
      activity: 'Residential new construction',
      citationType: 'Serious',
      standard: '1926.405',
      standardDescription: 'Electrical Safety - Wiring Design and Protection',
      penalty: 4215,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2023-002',
      date: '2023-05-22',
      activity: 'Roofing - tear-off and replacement',
      citationType: 'Other',
      standard: '1926.59',
      standardDescription: 'Hazard Communication',
      penalty: 1450,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2022-014',
      date: '2022-06-18',
      activity: 'Commercial roof repair',
      citationType: 'Willful',
      standard: '1926.502',
      standardDescription: 'Fall Protection Systems Criteria and Practices',
      penalty: 14025,
      status: 'Settled',
      contested: true,
      inspectorNarrative: 'Repeat violation. Employer had been cited for identical conditions on 2021-04-09. During inspection, three employees were observed working on a low-slope roof edge at 18 feet without guardrails, personal fall arrest, or safety nets. Employer representative stated "we don\'t use harnesses on flat roofs." This is the second willful citation for this standard at this employer.',
    },
    {
      id: 'CIT-2022-010',
      date: '2022-04-03',
      activity: 'Residential re-roof',
      citationType: 'Serious',
      standard: '1926.1053',
      standardDescription: 'Ladders',
      penalty: 3850,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2022-003',
      date: '2022-01-27',
      activity: 'Flat roof installation',
      citationType: 'Serious',
      standard: '1910.147',
      standardDescription: 'The Control of Hazardous Energy (Lockout/Tagout)',
      penalty: 4100,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2021-009',
      date: '2021-09-14',
      activity: 'Roof deck replacement',
      citationType: 'Serious',
      standard: '1926.501',
      standardDescription: 'Duty to Have Fall Protection',
      penalty: 5280,
      status: 'Settled',
      contested: false,
    },
    {
      id: 'CIT-2021-006',
      date: '2021-04-09',
      activity: 'Commercial roof maintenance',
      citationType: 'Serious',
      standard: '1926.502',
      standardDescription: 'Fall Protection Systems Criteria and Practices',
      penalty: 4670,
      status: 'Paid',
      contested: true,
    },
    {
      id: 'CIT-2021-002',
      date: '2021-02-15',
      activity: 'Residential re-roof',
      citationType: 'Other',
      standard: '1926.404',
      standardDescription: 'Wiring Design and Protection',
      penalty: 1320,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2020-011',
      date: '2020-07-22',
      activity: 'New construction roofing',
      citationType: 'Serious',
      standard: '1926.501',
      standardDescription: 'Duty to Have Fall Protection',
      penalty: 4890,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2020-007',
      date: '2020-05-10',
      activity: 'Flat roof repair',
      citationType: 'Serious',
      standard: '1926.1052',
      standardDescription: 'Stairways',
      penalty: 2540,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2019-004',
      date: '2019-08-30',
      activity: 'Residential tear-off',
      citationType: 'Other',
      standard: '1926.20',
      standardDescription: 'General Safety and Health Provisions',
      penalty: 1100,
      status: 'Paid',
      contested: false,
    },
    {
      id: 'CIT-2019-001',
      date: '2019-03-05',
      activity: 'Commercial re-roof',
      citationType: 'Serious',
      standard: '1926.501',
      standardDescription: 'Duty to Have Fall Protection',
      penalty: 3760,
      status: 'Paid',
      contested: false,
    },
  ],
  quarterlyViolations: quartersFrom(2020, 1, 24),
  trendData: [
    { month: '2020-01', score: 42 },
    { month: '2020-04', score: 48 },
    { month: '2020-07', score: 55 },
    { month: '2020-10', score: 50 },
    { month: '2021-01', score: 52 },
    { month: '2021-04', score: 58 },
    { month: '2021-07', score: 61 },
    { month: '2021-10', score: 57 },
    { month: '2022-01', score: 63 },
    { month: '2022-04', score: 70 },
    { month: '2022-07', score: 66 },
    { month: '2022-10', score: 68 },
    { month: '2023-01', score: 65 },
    { month: '2023-04', score: 60 },
    { month: '2023-07', score: 67 },
    { month: '2023-10', score: 71 },
    { month: '2024-01', score: 74 },
  ],
  peerGradeDistribution: [
    { grade: 'A', count: 18 },
    { grade: 'B', count: 32 },
    { grade: 'C', count: 27 },
    { grade: 'D', count: 14 },
    { grade: 'F', count: 9 },
  ],
};

export const allContractors: Contractor[] = [
  summitRoofing,
  {
    id: 'atlas-electric-inc',
    name: 'Atlas Electric Inc.',
    trade: 'Electrical',
    location: 'Dallas, TX',
    city: 'Dallas',
    state: 'TX',
    ein: '75-2214837',
    licenseNumber: 'TX-EC-184729',
    licensedSince: '2008',
    employees: 62,
    grade: 'B',
    gradeLabel: 'Good',
    gradeSummary: 'Based on 3 citations, 0 willful violations over 72 months',
    severityScore: 22,
    frequencyScore: 18,
    recencyScore: 12,
    responseScore: 85,
    violations36mo: 1,
    willfulViolations: 0,
    seriousViolations: 2,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Aug 2023',
    peerComparison: 'Better than 68% of electricians in Dallas metro',
    peerPercentile: 32,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'ironforge-structural',
    name: 'Ironforge Structural LLC',
    trade: 'Structural Steel',
    location: 'Houston, TX',
    city: 'Houston',
    state: 'TX',
    ein: '76-9103847',
    licenseNumber: 'TX-GC-392018',
    licensedSince: '2015',
    employees: 85,
    grade: 'F',
    gradeLabel: 'Critical Risk',
    gradeSummary: 'Based on 22 citations, 5 willful violations, and 2 fatality records over 72 months',
    severityScore: 94,
    frequencyScore: 88,
    recencyScore: 79,
    responseScore: 22,
    violations36mo: 14,
    willfulViolations: 5,
    seriousViolations: 12,
    otherViolations: 5,
    fatalityRecord: true,
    lastCitationDate: 'Jan 2024',
    peerComparison: 'Worse than 96% of steel erectors in Houston metro',
    peerPercentile: 96,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'clearwater-plumbing',
    name: 'Clearwater Plumbing Co.',
    trade: 'Plumbing',
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    ein: '74-5581203',
    licenseNumber: 'TX-MP-478201',
    licensedSince: '2003',
    employees: 28,
    grade: 'A',
    gradeLabel: 'Excellent',
    gradeSummary: 'Based on 1 citation, 0 willful violations over 72 months',
    severityScore: 8,
    frequencyScore: 5,
    recencyScore: 3,
    responseScore: 95,
    violations36mo: 0,
    willfulViolations: 0,
    seriousViolations: 0,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Nov 2020',
    peerComparison: 'Better than 94% of plumbers in Austin metro',
    peerPercentile: 6,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'granite-peak-construction',
    name: 'Granite Peak Construction',
    trade: 'General Contracting',
    location: 'San Antonio, TX',
    city: 'San Antonio',
    state: 'TX',
    ein: '82-3340192',
    licenseNumber: 'TX-GC-559201',
    licensedSince: '2012',
    employees: 120,
    grade: 'C',
    gradeLabel: 'Caution',
    gradeSummary: 'Based on 7 citations, 1 willful violation over 72 months',
    severityScore: 45,
    frequencyScore: 38,
    recencyScore: 52,
    responseScore: 60,
    violations36mo: 4,
    willfulViolations: 1,
    seriousViolations: 4,
    otherViolations: 2,
    fatalityRecord: false,
    lastCitationDate: 'Dec 2023',
    peerComparison: 'Worse than 48% of general contractors in San Antonio metro',
    peerPercentile: 48,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'pinnacle-hvac',
    name: 'Pinnacle HVAC Services',
    trade: 'HVAC',
    location: 'Fort Worth, TX',
    city: 'Fort Worth',
    state: 'TX',
    ein: '68-7823194',
    licenseNumber: 'TX-HV-201847',
    licensedSince: '2016',
    employees: 34,
    grade: 'B',
    gradeLabel: 'Good',
    gradeSummary: 'Based on 4 citations, 0 willful violations over 72 months',
    severityScore: 28,
    frequencyScore: 22,
    recencyScore: 18,
    responseScore: 78,
    violations36mo: 2,
    willfulViolations: 0,
    seriousViolations: 3,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Jun 2023',
    peerComparison: 'Better than 72% of HVAC contractors in Fort Worth metro',
    peerPercentile: 28,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'redline-demolition',
    name: 'Redline Demolition Inc.',
    trade: 'Demolition',
    location: 'Houston, TX',
    city: 'Houston',
    state: 'TX',
    ein: '47-6610283',
    licenseNumber: 'TX-DM-102837',
    licensedSince: '2018',
    employees: 55,
    grade: 'D',
    gradeLabel: 'High Risk',
    gradeSummary: 'Based on 11 citations, 2 willful violations over 72 months',
    severityScore: 71,
    frequencyScore: 58,
    recencyScore: 65,
    responseScore: 35,
    violations36mo: 7,
    willfulViolations: 2,
    seriousViolations: 6,
    otherViolations: 3,
    fatalityRecord: false,
    lastCitationDate: 'Feb 2024',
    peerComparison: 'Worse than 78% of demolition contractors in Houston metro',
    peerPercentile: 78,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'blue-ridge-painting',
    name: 'Blue Ridge Painting Co.',
    trade: 'Painting',
    location: 'Denver, CO',
    city: 'Denver',
    state: 'CO',
    ein: '84-2910473',
    licenseNumber: 'CO-PN-472910',
    licensedSince: '2014',
    employees: 22,
    grade: 'A',
    gradeLabel: 'Excellent',
    gradeSummary: 'Based on 2 citations, 0 willful violations over 72 months',
    severityScore: 10,
    frequencyScore: 8,
    recencyScore: 5,
    responseScore: 92,
    violations36mo: 0,
    willfulViolations: 0,
    seriousViolations: 1,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Apr 2021',
    peerComparison: 'Better than 91% of painting contractors in Denver metro',
    peerPercentile: 9,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: ' cornerstone-masonry',
    name: 'Cornerstone Masonry',
    trade: 'Masonry',
    location: 'Phoenix, AZ',
    city: 'Phoenix',
    state: 'AZ',
    ein: '86-4418290',
    licenseNumber: 'AZ-MY-291847',
    licensedSince: '2009',
    employees: 41,
    grade: 'C',
    gradeLabel: 'Caution',
    gradeSummary: 'Based on 6 citations, 1 willful violation over 72 months',
    severityScore: 42,
    frequencyScore: 35,
    recencyScore: 44,
    responseScore: 55,
    violations36mo: 3,
    willfulViolations: 1,
    seriousViolations: 3,
    otherViolations: 2,
    fatalityRecord: false,
    lastCitationDate: 'Sep 2023',
    peerComparison: 'Worse than 44% of masonry contractors in Phoenix metro',
    peerPercentile: 44,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'summit-landscaping',
    name: 'Summit Landscaping & Excavation',
    trade: 'Excavation',
    location: 'Nashville, TN',
    city: 'Nashville',
    state: 'TN',
    ein: '62-1184029',
    licenseNumber: 'TN-EX-847201',
    licensedSince: '2017',
    employees: 38,
    grade: 'D',
    gradeLabel: 'High Risk',
    gradeSummary: 'Based on 9 citations, 1 willful violation over 72 months',
    severityScore: 68,
    frequencyScore: 52,
    recencyScore: 58,
    responseScore: 40,
    violations36mo: 5,
    willfulViolations: 1,
    seriousViolations: 5,
    otherViolations: 3,
    fatalityRecord: false,
    lastCitationDate: 'Nov 2023',
    peerComparison: 'Worse than 75% of excavation contractors in Nashville metro',
    peerPercentile: 75,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'pacific-coast-framing',
    name: 'Pacific Coast Framing',
    trade: 'Framing',
    location: 'Seattle, WA',
    city: 'Seattle',
    state: 'WA',
    ein: '91-3382017',
    licenseNumber: 'WA-FR-019283',
    licensedSince: '2019',
    employees: 30,
    grade: 'B',
    gradeLabel: 'Good',
    gradeSummary: 'Based on 3 citations, 0 willful violations over 72 months',
    severityScore: 20,
    frequencyScore: 15,
    recencyScore: 10,
    responseScore: 82,
    violations36mo: 1,
    willfulViolations: 0,
    seriousViolations: 2,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Mar 2023',
    peerComparison: 'Better than 76% of framing contractors in Seattle metro',
    peerPercentile: 24,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'heartland-concrete',
    name: 'Heartland Concrete Works',
    trade: 'Concrete',
    location: 'Oklahoma City, OK',
    city: 'Oklahoma City',
    state: 'OK',
    ein: '73-8192044',
    licenseNumber: 'OK-CC-382017',
    licensedSince: '2013',
    employees: 56,
    grade: 'F',
    gradeLabel: 'Critical Risk',
    gradeSummary: 'Based on 18 citations, 4 willful violations, and 1 fatality record over 72 months',
    severityScore: 89,
    frequencyScore: 82,
    recencyScore: 75,
    responseScore: 18,
    violations36mo: 11,
    willfulViolations: 4,
    seriousViolations: 10,
    otherViolations: 4,
    fatalityRecord: true,
    lastCitationDate: 'Dec 2023',
    peerComparison: 'Worse than 94% of concrete contractors in Oklahoma City metro',
    peerPercentile: 94,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'silverline-drywall',
    name: 'Silverline Drywall Inc.',
    trade: 'Drywall',
    location: 'Las Vegas, NV',
    city: 'Las Vegas',
    state: 'NV',
    ein: '88-2201937',
    licenseNumber: 'NV-DW-918273',
    licensedSince: '2020',
    employees: 18,
    grade: 'A',
    gradeLabel: 'Excellent',
    gradeSummary: 'Based on 1 citation, 0 willful violations over 72 months',
    severityScore: 6,
    frequencyScore: 4,
    recencyScore: 2,
    responseScore: 97,
    violations36mo: 0,
    willfulViolations: 0,
    seriousViolations: 0,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Jan 2021',
    peerComparison: 'Better than 97% of drywall contractors in Las Vegas metro',
    peerPercentile: 3,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
];

export const homeownerSavedContractors = [
  { ...summitRoofing, savedDate: '2024-04-12', gradeChange: null },
  { ...allContractors[1], savedDate: '2024-03-28', gradeChange: null },
  { ...allContractors[3], savedDate: '2024-02-15', gradeChange: 'down' as const },
  { ...allContractors[4], savedDate: '2024-01-20', gradeChange: null },
];

export const searchResults = [
  summitRoofing,
  {
    id: 'summit-roofing-austin',
    name: 'Summit Roofing & Restoration',
    trade: 'Roofing',
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    ein: '74-9102837',
    licenseNumber: 'TX-ROC-102938',
    licensedSince: '2019',
    employees: 15,
    grade: 'B' as Grade,
    gradeLabel: 'Good',
    gradeSummary: 'Based on 2 citations, 0 willful violations over 72 months',
    severityScore: 18,
    frequencyScore: 12,
    recencyScore: 8,
    responseScore: 80,
    violations36mo: 1,
    willfulViolations: 0,
    seriousViolations: 1,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'May 2023',
    peerComparison: 'Better than 74% of roofers in Austin metro',
    peerPercentile: 26,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
  {
    id: 'summit-roofing-dallas',
    name: 'Summit Roofing & Siding Co.',
    trade: 'Roofing & Siding',
    location: 'Dallas, TX',
    city: 'Dallas',
    state: 'TX',
    ein: '75-3382019',
    licenseNumber: 'TX-ROC-582019',
    licensedSince: '2016',
    employees: 31,
    grade: 'C' as Grade,
    gradeLabel: 'Caution',
    gradeSummary: 'Based on 5 citations, 1 willful violation over 72 months',
    severityScore: 38,
    frequencyScore: 30,
    recencyScore: 42,
    responseScore: 50,
    violations36mo: 3,
    willfulViolations: 1,
    seriousViolations: 3,
    otherViolations: 1,
    fatalityRecord: false,
    lastCitationDate: 'Jul 2023',
    peerComparison: 'Worse than 45% of roofers in Dallas metro',
    peerPercentile: 45,
    citations: [],
    quarterlyViolations: [],
    trendData: [],
    peerGradeDistribution: [],
  },
];
